spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Sangramjit786/config-server-repo.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///C://Users//Rohit//Documents//eazybytes//config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

logging:
  level:
    org.springframework.cloud.bus: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit: DEBUG

server:
  port: 8071